### ISSUE TITLE
Comparing to upstream

### ISSUE THREAD

**Issue by Gitoffthelawn** [magnus-ISU/videospeed#2]
I would like to compare all the source code changes you've made to upstream (https://github.com/codebicycle/videospeed).

I see you've been busy and are currently 56 commits ahead. Well done!

I seem to recall an easy way to view the changes in a fork for each source file, but for some reason I don't see it right now.

Can you help?

(I tried using `blame`, but that shows changes before your fork.)

**Comment by magnus-ISU** [comment]
```
git clone https://github.com/magnus-ISU/videospeed
cd videospeed
git diff origin/firefox-port
```
Optional bling: install `diff-so-fancy` and configure it

I apologize for `options.html`, the file is almost exactly the same except there is a `type="module"` near the beginning and the `controllerSize` config option is new. But [the chromium MR for dark theme](https://github.com/igrigorik/videospeed/pull/901) (which at some point I will have to actually revisit, the current dark theme is better than before but not great) removed two levels of indentation everywhere, so a simple diff sees the entire file as having changed.

**Comment by Gitoffthelawn** [comment]
Thank you.  That'll work fine.

Regarding `options.html`, I can just run a simple post-filter on it.  No problem.

**Comment by Gitoffthelawn** [comment]
BTW, do you know of any way to do that with the GitHub web-app?  I thought there was an easy way, but I'm not seeing it now.

**Comment by magnus-ISU** [comment]
Ah, also should mention that `git log` can show you the whole commit path back through history and you can choose any commit to diff by its hash or diff 2 commits with `git diff HEAD~2 HEAD~1` for example, which will show the differences between the third-to-last commit and the second-to-last one.

No idea. I know on a MR you can see files changed in the MR easily, but sadly that doesn't seem to be a generic UI that can choose any 2 commits.

**Comment by Gitoffthelawn** [comment]
> Ah, also should mention that `git log` can show you the whole commit path back through history and you can choose any commit to diff by its hash or diff 2 commits with `git diff HEAD~2 HEAD~1` for example, which will show the differences between the third-to-last commit and the second-to-last one.

Thanks.

> About web diff view, no idea. I know on a MR you can see files changed in the MR easily, but sadly that doesn't seem to be a generic UI that can choose any 2 commits.

Ah, that's exactly what I want.  I can't find a way either.  C'est la vie.

**Comment by magnus-ISU** [comment]
You can actually see a diff when creating a PR, so one possibility would be to fork this, click to create a PR to codebicycle, but don't actually go through with it, just see the differences.

Since this isn't actually an issue with the program I'll close this.
