### ISSUE TITLE
Spamming Firefox console with Debug statements

### ISSUE THREAD

**Issue by arandomguysomewhere** [magnus-ISU/videospeed#29]
Hi, looks like the addon is shipping with debug on and this is causing spam in the Firefox console with every keypress being logged. This seems to be a result of the Firefox addon being very outdated compared to the Chrome build, please update it.

**Comment by nethew** [comment]
@magnus-ISU Please publish a new version of the addon. The debug spam has already been fixed here, but not in a new version on addons.mozilla.org.

Of course having a switch in settings for turning the debugging messages on or off wold be even better. ;) But turning them off is enough.

**Comment by nethew** [comment]
@magnus-ISU Thank you very much for the new version!
The console debug spam is gone.

**Comment by arandomguysomewhere** [comment]
@nethew Thanks for pointing this out! Closing this issue after the latest update.
