### ISSUE TITLE
Improvement: merge options.css and popup.css into a single videospeed.css

### ISSUE THREAD

**Issue by magnus-ISU** [magnus-ISU/videospeed#8]
Currently, the popup.css has no dark theme because I neglected it, and there is like to be duplication of some ideas (color definitions, etc) in both files also. That's indicative of a problem where we could simplify things.

Also, fix the crappy dark theme having blinding white buttons. I suspect after this merge it should be easier to see how to do that.

**Comment by Gitoffthelawn** [comment]
I wrote a dark theme for the original VSC... let me see where it's at...

**Comment by Gitoffthelawn** [comment]
I found how I handled that.  I wrote a generic dark theme for the majority of Firefox extension settings pages.  I covered VSC under that.

**Comment by Gitoffthelawn** [comment]
BTW, I'm done monkeying around with the code for now.  :)
